---
- name: Update boxes
  hosts: boxes
  ignore_unreachable: true
  gather_facts: false

  tasks:
    - name: Copy apt script
      copy:
        src: "{{ inventory_hostname }}/scripts/apt.sh"
        dest: /root/apt.sh
        mode: 0755

    - name: Execute apt script
      shell: ./apt.sh
      args:
        executable: /bin/bash
        chdir: /root
      changed_when: true

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        # Run the equivalent of apt-get update command on all servers
        update_cache: true
        # Do not use the aptitude command
        # instead use the apt-get command on Debian/Ubuntu boxes
        force_apt_get: true
        # Update the apt cache if it's older than the cache_valid_time.
        # This option is set in seconds
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      apt:
        upgrade: dist # Run the equivalent of ‘apt-get upgrade’
        force_apt_get: true # Use apt-get instead of aptitude
        autoremove: true # remove unused dependency packages

    - name: Check if a reboot is needed on all servers
      stat:
        path: /var/run/reboot-required
      # Save a result in, and we are going to use it as follows to reboot the box
      register: reboot_required_file

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 10
        # Execute uptime command on the rebooted server and expect success from
        # to determine the machine is ready for further tasks
        test_command: uptime
      # First, check that the file named /var/run/reboot-required exists using a
      # variable named reboot_required_file.
      # The reboot module will only work if that file exists, and it is enforced
      # using ‘when: reboot_required_file.stat.exists’ Ansible condition.
      when: reboot_required_file.stat.exists
