---
all:
  children:
    boxes:
      hosts:
        debian12:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2500
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
        ubuntu22.04:
          ansible_ssh_host: 127.0.1.1
          ansible_ssh_port: 2501
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
