---
all:
  children:
    virtualbox:
      hosts:
        debian12:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2500
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
          host_folder: debian12
        ubuntu22.04:
          ansible_ssh_host: 127.0.1.1
          ansible_ssh_port: 2501
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
          host_folder: ubuntu22.04
    libvirt:
      hosts:
        debian12-libvirt:
          ansible_ssh_host: 192.168.122.201
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
          host_folder: debian12
        ubuntu22.04-libvirt:
          ansible_ssh_host: 192.168.122.200
          ansible_ssh_user: root
          ansible_ssh_private_key_file: ./files/id_rsa.devel
          host_folder: ubuntu22.04
    boxes:
      children:
        virtualbox:
        libvirt:
